[project]
name = "akashic-perflogger"
version = "0.1.2"
description = "Python performance logging library"
authors = [
    { name = "Akasha Mouginot", email = "akasha.mouginot@protonmail.com" }
]
requires-python = ">=3.14"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",

    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",

    "Topic :: Software Development :: Libraries :: Python Modules",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
keywords = ["performance", "testing"]

[project.urls]
Homepage = "https://github.com/ewigael/perflogger"
Changelog = "https://github.com/ewigael/perflogger/blob/main/docs/CHANGELOG.md"
Issues = "https://github.com/ewigael/perflogger/issues"
Readme = " https://github.com/ewigael/perflogger/blob/main/README.md"

[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
